@echo off
echo Activating virtual environment...
call venv\Scripts\activate

echo Starting Django development server...
python manage.py runserver

echo Press any key to exit...
pause > nul

echo Deactivating virtual environment...
deactivate